name: Lint, Build & Deploy (GitHub Pages - Next.js static)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

env:
  # Set this to your repository name for project pages (username.github.io/<repo>)
  # Leave blank for user/organization pages (username.github.io)
  NEXT_PUBLIC_REPO_NAME: "" # e.g., "my-next-repo"

jobs:
  verify:
    name: Lint & Build (PR checks)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Export static site
        run: npm run export

      - name: Upload build artifact (debugging)
        uses: actions/upload-artifact@v4
        with:
          name: next-export-out
          path: out

  build:
    name: Build & Upload Pages Artifact
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Export static site
        run: npm run export

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
